# These are variables that are utilized by pretty much all playbooks.
  - osp_version: 14
  - uc_user: stack
  - uc_pass: stack
  - tripleo_heat_templates: /usr/share/openstack-tripleo-heat-templates
  - stack_templates: /home/stack/templates
  - deploy_script: /home/stack/overcloud_deploy.sh
  - overcloud_timezone: 'US/Eastern'
